# Generated by Django 5.2.14 on 2026-05-26 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('scope1', 'Scope 1'), ('scope2', 'Scope 2'), ('scope3', 'Scope 3')], max_length=50)),
                ('activity_type', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('normalized_unit', models.CharField(max_length=100)),
                ('emission_factor', models.FloatField()),
                ('emissions_kg_co2e', models.FloatField()),
                ('reporting_date', models.DateField()),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspicious', 'Suspicious')], default='pending', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.datasource')),
            ],
        ),
    ]
